export const AUTH_ERROR_CODES = {
	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	TOKEN_MISSING: "TOKEN_MISSING",
	TOKEN_INVALID: "TOKEN_INVALID",
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type AuthErrorCode =
	(typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
