export const BOOK_ERROR_CODES = {
	VALIDATION_ERROR: "BOOK_VALIDATION_ERROR",
	NOT_FOUND: "BOOK_NOT_FOUND",
	ISBN_LOOKUP_FAILED: "BOOK_ISBN_LOOKUP_FAILED",
	REGISTRANT_NOT_FOUND: "BOOK_REGISTRANT_NOT_FOUND",
	BORROWER_NOT_FOUND: "BOOK_BORROWER_NOT_FOUND",
	INTERNAL_ERROR: "BOOK_INTERNAL_ERROR",
} as const;

export type BookErrorCode =
	(typeof BOOK_ERROR_CODES)[keyof typeof BOOK_ERROR_CODES];

export const BOOK_STATUS_LABELS: Record<string, string> = {
	STORED: "保管",
	LENDING: "貸与",
};
