export const EMPLOYEE_ERROR_CODES = {
	VALIDATION_ERROR: "EMPLOYEE_VALIDATION_ERROR",
	NOT_FOUND: "EMPLOYEE_NOT_FOUND",
	EMAIL_ALREADY_EXISTS: "EMPLOYEE_EMAIL_ALREADY_EXISTS",
	DEPARTMENT_NOT_FOUND: "DEPARTMENT_NOT_FOUND",
	INTERNAL_ERROR: "EMPLOYEE_INTERNAL_ERROR",
} as const;

export type EmployeeErrorCode =
	(typeof EMPLOYEE_ERROR_CODES)[keyof typeof EMPLOYEE_ERROR_CODES];

export const EMPLOYEE_STATUS_LABELS: Record<string, string> = {
	ACTIVE: "在籍",
	ON_LEAVE: "休職中",
	RETIRED: "退職済み",
};
