export const PROJECT_ERROR_CODES = {
	NOT_FOUND: "PROJECT_NOT_FOUND",
	INTERNAL_ERROR: "PROJECT_INTERNAL_ERROR",
	VALIDATION_ERROR: "PROJECT_VALIDATION_ERROR",
	NAME_ALREADY_EXISTS: "PROJECT_NAME_ALREADY_EXISTS",
	LEADER_NOT_FOUND: "PROJECT_LEADER_NOT_FOUND",
	MEMBER_NOT_FOUND: "PROJECT_MEMBER_NOT_FOUND",
	LEADER_IN_MEMBERS: "PROJECT_LEADER_IN_MEMBERS",
} as const;

export type ProjectErrorCode =
	(typeof PROJECT_ERROR_CODES)[keyof typeof PROJECT_ERROR_CODES];
